# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: forbid-submodules

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.44.0
  #   hooks:
  #     - id: markdownlint
  #       # Disable rule MD013: maximum line length 80 columns
  #       args: [ --disable=MD013 ]

  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: v0.6.13
  #   hooks:
  #     - id: cmake-format
  #     - id: cmake-lint
  #       # Disable rule C0307: indentation width, because it does not match the default CLion indentation.
  #       args: [ --line-width=120, --disabled-codes=C0307 ]

  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        args: [ "--filter=
                 -build/c++11,
                 -build/c++17,
                 -build/namespaces,
                 -legal/copyright,
                 -whitespace/indent_namespace",
                "--linelength=120" ]
