///
/// SPDX-License-Identifier: Apache-2.0
/// Copyright 2024-2025 anderewrey
///

#pragma once

#include <grpcpp/client_context.h>

#include <memory>
#include <utility>

#include "rg_service/route_guide_service.h"

#include "applications/reactor/reactor_client.h"

/************************
 * Active Object Pattern: Specialized Method Request components
 * These RouteGuide-specific reactors specialize the generic Method Request classes
 * from reactor_client.h. See reactor_client.md for architecture details.
 ************************/

/************************
 * ClientReactor/GetFeature: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::GetFeature {
/// Specialized callback slots for RouteGuide::GetFeature unary RPC client
using Callbacks = RpcReactor::Client::ActiveUnaryCallbacks<ResponseT>;

/// Specialized reactor class for RouteGuide::GetFeature unary RPC client.
/// Specializes the generic ActiveUnaryReactor (Method Request component).
class ClientReactor final : public RpcReactor::Client::ActiveUnaryReactor<ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method with the address pointer where
  /// the response is wanted to be written. The context and the callbacks objects are moved to the
  /// underlying generic class.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param request to send to the server
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                const RequestT& request,
                Callbacks&& cbs)
      : ActiveUnaryReactor(std::move(context), std::move(cbs)) {
    // (Point 1.2, 1.3) async RPC call
    stub.async()->GetFeature(context_.get(), &request, &response_, this);
    // (Point 1.4, 1.5) Starting RPC call, send request to server
    StartCall();
  }
};
}  // namespace routeguide::GetFeature

/************************
 * ClientReactor/ListFeatures: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::ListFeatures {
/// Specialized callback slots for RouteGuide::ListFeatures stream-reader RPC client
using Callbacks = RpcReactor::Client::ActiveReadCallbacks<ResponseT>;

/// Specialized reactor class for RouteGuide::ListFeatures stream-reader RPC client.
/// Specializes the generic ActiveReadReactor (Method Request component).
class ClientReactor final : public RpcReactor::Client::ActiveReadReactor<ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method and start the stream reading
  /// with the address pointer where the response is wanted to be written.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param request to send to the server
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                const RequestT& request,
                Callbacks&& cbs)
      : ActiveReadReactor(std::move(context), std::move(cbs)) {
    // (Point 1.2, 1.3) async RPC call
    stub.async()->ListFeatures(context_.get(), &request, this);
    // (Point 1.4) Starting reading
    StartRead(&response_);
    // (Point 1.5, 1.6) Starting RPC call, send request to server
    StartCall();
  }
};
}  // namespace routeguide::ListFeatures
