///
/// SPDX-License-Identifier: Apache-2.0
/// Copyright 2024 anderewrey
///

#pragma once

#include <grpcpp/client_context.h>

#include <memory>
#include <utility>

#include "rg_service/route_guide_service.h"

#include "applications/reactor/reactor_client.h"

/************************
 * Active Object Pattern: Specialized Method Request components
 * These RouteGuide-specific reactors specialize the generic Method Request classes
 * from reactor_client.h. See reactor_client.md for architecture details.
 ************************/

/************************
 * ClientReactor/GetFeature: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::GetFeature {
/// Specialized callback slots for RouteGuide::GetFeature unary RPC client
using Callbacks = RpcReactor::Client::ActiveUnaryCallbacks<ResponseT>;

/// Specialized reactor class for RouteGuide::GetFeature unary RPC client.
/// Specializes the generic ActiveUnaryReactor (Method Request component).
class ClientReactor final : public RpcReactor::Client::ActiveUnaryReactor<ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method with the address pointer where
  /// the response is wanted to be written. The context and the callbacks objects are moved to the
  /// underlying generic class.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param request to send to the server
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                const RequestT& request,
                Callbacks&& cbs)
      : ActiveUnaryReactor(std::move(context), std::move(cbs)) {
    // (Point 1.2, 1.3) async RPC call
    stub.async()->GetFeature(context_.get(), &request, &response_, this);
    // (Point 1.4, 1.5) Starting RPC call, send request to server
    StartCall();
  }
};
}  // namespace routeguide::GetFeature

/************************
 * ClientReactor/ListFeatures: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::ListFeatures {
/// Specialized callback slots for RouteGuide::ListFeatures stream-reader RPC client
using Callbacks = RpcReactor::Client::ActiveReadCallbacks<ResponseT>;

/// Specialized reactor class for RouteGuide::ListFeatures stream-reader RPC client.
/// Specializes the generic ActiveReadReactor (Method Request component).
class ClientReactor final : public RpcReactor::Client::ActiveReadReactor<ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method and start the stream reading
  /// with the address pointer where the response is wanted to be written.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param request to send to the server
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                const RequestT& request,
                Callbacks&& cbs)
      : ActiveReadReactor(std::move(context), std::move(cbs)) {
    // (Point 1.2, 1.3) async RPC call
    stub.async()->ListFeatures(context_.get(), &request, this);
    // (Point 1.4) Starting reading
    StartRead(&response_);
    // (Point 1.5, 1.6) Starting RPC call, send request to server
    StartCall();
  }
};
}  // namespace routeguide::ListFeatures

/************************
 * ClientReactor/RecordRoute: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::RecordRoute {
/// Specialized callback slots for RouteGuide::RecordRoute stream-writer RPC client
using Callbacks = RpcReactor::Client::ActiveWriteCallbacks<RequestT, ResponseT>;

/// Specialized reactor class for RouteGuide::RecordRoute stream-writer RPC client.
/// Specializes the generic ActiveWriteReactor (Method Request component).
class ClientReactor final : public RpcReactor::Client::ActiveWriteReactor<RequestT, ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method with the address pointer where
  /// the response is wanted to be written.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                Callbacks&& cbs)
      : ActiveWriteReactor(std::move(context), std::move(cbs)) {
    // async RPC call - gRPC writes the final response into response_ directly when the RPC
    // completes; there is no separate read event for a client-streaming RPC's response.
    stub.async()->RecordRoute(context_.get(), &response_, this);
    // Starting RPC call
    StartCall();
  }
};
}  // namespace routeguide::RecordRoute

/************************
 * ClientReactor/RouteChat: Following code belongs to the API implementation
 * That code could be auto-generated by jinja template files (because of the stub.async()->rpc_method() call).
 ************************/
namespace routeguide::RouteChat {
/// Specialized callback slots for RouteGuide::RouteChat bidirectional streaming RPC client
using Callbacks = RpcReactor::Client::ActiveBidiCallbacks<RequestT, ResponseT>;

/// Specialized reactor class for RouteGuide::RouteChat bidirectional streaming RPC client.
/// Specializes the generic ActiveBidiReactor (Method Request component).
///
/// Bidirectional streaming allows interleaved message flow:
/// - Client can send RouteNote messages via SendRequest() at any time
/// - Server can send RouteNote responses at any time via OnReadDone()
/// - Read and write streams operate independently
/// - EventLoop integration: callbacks can trigger TriggerEvent() to dispatch to application thread
///
/// Inherited methods from ActiveBidiReactor:
/// - SendRequest(const RouteNote&): Send a message to the server
/// - CloseRequestStream(): Signal end of client requests (server may continue sending)
/// - GetResponse(RouteNote&): Extract received response via swap
/// - TryCancel(): Cancel the RPC from any thread
/// - Status(): Get completion status after OnDone()
class ClientReactor final : public RpcReactor::Client::ActiveBidiReactor<RequestT, ResponseT> {
 public:
  /// Constructor of the specialized class. It calls the RPC method and starts the stream reading
  /// with the address pointer where the response is wanted to be written.
  /// @param stub of the RouteGuide API
  /// @param context given to the reactor and is associated with the called RPC method
  /// @param cbs given to the reactor to be used as callable functions
  ClientReactor(RouteGuide::Stub& stub,
                std::unique_ptr<grpc::ClientContext> context,
                Callbacks&& cbs)
      : ActiveBidiReactor(std::move(context), std::move(cbs)) {
    // (Point 1.2, 1.3) async RPC call - establishes bidirectional stream
    stub.async()->RouteChat(context_.get(), this);
    // (Point 1.4) Starting reading
    StartRead(&response_);
    // (Point 1.5, 1.6) Starting RPC call, send request to server
    StartCall();
  }
};
}  // namespace routeguide::RouteChat
